# Generated by Django 5.2.1 on 2025-08-06 17:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorReputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("fraud_score", models.FloatField(default=0.0)),
                ("total_complaints", models.IntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("avg_engagement_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Creator Reputation",
                "verbose_name_plural": "Creator Reputations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "channel_link",
                    models.CharField(
                        help_text="A channel with this link already exists.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="N/A", max_length=255)),
                ("pp_url", models.CharField(blank=True, max_length=255, null=True)),
                ("subscribers", models.PositiveBigIntegerField(default=0)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ET", "Ethiopia"),
                            ("KE", "Kenya"),
                            ("SA", "Saudi Arabia"),
                            ("AE", "UAE"),
                            ("RU", "Russia"),
                        ],
                        default="ET",
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Africa/Addis_Ababa", "Africa/Addis_Ababa"),
                            ("Africa/Nairobi", "Africa/Nairobi"),
                            ("America/New_York", "America/New_York"),
                            ("Europe/London", "Europe/London"),
                            ("Asia/Tokyo", "Asia/Tokyo"),
                            ("Australia/Sydney", "Australia/Sydney"),
                            ("UTC", "UTC"),
                        ],
                        default="Africa/Addis_Ababa",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "min_cpm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "repost_preference",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("day", "Daily"),
                            ("week", "Weekly"),
                            ("hour", "Hourly"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                (
                    "repost_preference_frequency",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("auto_publish", models.BooleanField(default=True)),
                ("ml_score", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("activation_code", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ManyToManyField(
                        limit_choices_to={"is_active": True},
                        related_name="channels",
                        to="core.category",
                    ),
                ),
                (
                    "language",
                    models.ManyToManyField(
                        help_text="Select all that apply to your channel.",
                        related_name="channels",
                        to="core.language",
                    ),
                ),
            ],
        ),
    ]
