# Generated by Django 5.2.1 on 2025-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorchannel",
            name="last_score_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
