# Generated by Django 5.2.1 on 2025-10-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0003_creatorchannel_last_score_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorreputation",
            name="creator_channel",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reputations",
                to="creators.creatorchannel",
            ),
            preserve_default=False,
        ),
    ]
