# Generated by Django 5.2.1 on 2025-10-07 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0004_creatorreputation_creator_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorreputation",
            name="creator",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_reputation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="creatorreputation",
            name="creator_channel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reputation",
                to="creators.creatorchannel",
            ),
        ),
    ]
