# Generated by Django 5.2.1 on 2025-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0005_alter_creatorreputation_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorreputation",
            name="estimated_cost_max",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Estimated Campaign Cost (Max)",
            ),
        ),
        migrations.AddField(
            model_name="creatorreputation",
            name="estimated_cost_min",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Estimated Campaign Cost (Min)",
            ),
        ),
        migrations.AddField(
            model_name="creatorreputation",
            name="estimated_views_avg",
            field=models.IntegerField(
                default=0, verbose_name="Estimated Views (Average)"
            ),
        ),
        migrations.AddField(
            model_name="creatorreputation",
            name="estimated_views_max",
            field=models.IntegerField(
                default=0, verbose_name="Estimated Views (Top Post)"
            ),
        ),
        migrations.AlterField(
            model_name="creatorreputation",
            name="avg_engagement_rate",
            field=models.FloatField(
                default=0.0, verbose_name="Soft Engagement Rate (%)"
            ),
        ),
    ]
