# Generated by Django 5.2.1 on 2025-10-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0006_creatorreputation_estimated_cost_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorreputation",
            name="creator",
        ),
    ]
