# Generated by Django 5.2.1 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("escrow_lock", "Lock"),
                    ("escrow_unlock", "Unlock"),
                    ("spend", "Spend"),
                    ("gain", "Earned from Campaign"),
                    ("escrow_refund", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
