# Generated by Django 5.2.1 on 2025-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balance",
            old_name="locked",
            new_name="escrow",
        ),
        migrations.AddField(
            model_name="balance",
            name="pending_withdrawals",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="after_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="sub_balance",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("escrow", "Escrow"),
                    ("pending_withdrawals", "Pending Withdrawals"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="reference",
            field=models.CharField(default="default-wdr-ref", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("spend", "Spend"),
                    ("earning", "Earning"),
                ],
                max_length=20,
            ),
        ),
    ]
