# Generated by Django 5.2.1 on 2025-08-06 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(max_length=20)),
                ("text_content", models.TextField(max_length=200)),
                ("img_url", models.CharField(max_length=255, null=True)),
                ("link_url", models.URLField(blank=True, null=True)),
                ("brand_name", models.CharField(blank=True, max_length=50, null=True)),
                ("ml_score", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("reposts", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_reactions", models.IntegerField(default=0)),
                ("total_replies", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("forwards", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "is_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the cost has been                                           deducted from the advertiser's wallet",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("brand_awareness", "Brand Awareness"),
                            ("engagement", "Engagement"),
                            ("conversion", "Conversion"),
                            ("traffic", "Traffic"),
                        ],
                        default="brand_awareness",
                        max_length=20,
                    ),
                ),
                (
                    "initial_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cpm", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("views_frequency_cap", models.IntegerField(default=1)),
                ("targeting_regions", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("stopped", "Stopped"),
                            ("declined", "Declined"),
                        ],
                        default="stopped",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="", null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [
                    ("pause_campaign", "Can pause campaigns"),
                    ("start_campaign", "Can start campaigns"),
                    ("activate_campaign", "Can activate reviewed campaigns"),
                    ("decline_campaign", "Can decline reviewed campaigns"),
                    ("resubmit_campaign", "Can resubmit declined campaigns"),
                    (
                        "remoderate_campaign",
                        "Can initiat remoderation active campaign campaigns",
                    ),
                    ("restart_campaign", "Can restart stopped campaigns"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlacementMatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_on", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "winning_bid_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("repost_count", models.IntegerField(default=0)),
                ("max_reposts", models.IntegerField(default=3)),
                ("preference_score", models.FloatField(default=1.0)),
                (
                    "content_platform_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad",
                    models.ForeignKey(
                        limit_choices_to={
                            "campaign__status__in": ["on_hold", "active"],
                            "is_active": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="core.ad",
                    ),
                ),
            ],
        ),
    ]
