# Generated by Django 5.2.1 on 2025-08-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adplacement",
            name="channel",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "status": "verified"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_placements",
                to="creators.creatorchannel",
            ),
        ),
        migrations.AddField(
            model_name="adperformance",
            name="ad_placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to="core.adplacement",
            ),
        ),
    ]
