# Generated by Django 5.2.1 on 2025-08-06 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="advertiser",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "advertiser"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="core.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="targeting_categories",
            field=models.ManyToManyField(related_name="campaigns", to="core.category"),
        ),
        migrations.AlterUniqueTogether(
            name="language",
            unique_together={("name", "code")},
        ),
        migrations.AddField(
            model_name="campaign",
            name="targeting_languages",
            field=models.ManyToManyField(
                help_text="Select all languages that you are targeting",
                related_name="campaigns",
                to="core.language",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placementmatchlog",
            name="ad_placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.adplacement"
            ),
        ),
        migrations.AddField(
            model_name="placementmatchlog",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_placements_match_log",
                to="core.campaign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adplacement",
            unique_together={("ad", "channel")},
        ),
        migrations.AlterUniqueTogether(
            name="adperformance",
            unique_together={("ad_placement", "timestamp")},
        ),
        migrations.AlterUniqueTogether(
            name="campaign",
            unique_together={("name", "advertiser", "status")},
        ),
    ]
