# Generated by Django 5.2.1 on 2025-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adplacement",
            name="content_platform_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
