# Generated by Django 5.2.1 on 2025-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_adplacement_content_platform_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adplacement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("stopped", "Stopped"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                ],
                default="stopped",
                max_length=20,
            ),
        ),
    ]
