# Generated by Django 5.2.1 on 2025-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_adplacement_status_alter_campaign_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
