# Generated by Django 5.2.1 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_ad_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="adperformance",
            name="time_delta",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
