# Generated by Django 5.2.1 on 2025-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_adperformance_time_delta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adplacement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("running", "Live"),
                    ("rejected", "Rejected"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
