# Generated by Django 5.2.1 on 2025-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_adplacement_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ad_action", "Ad Action"),
                    ("earning", "Earning"),
                    ("withdrawal", "Withdrawal"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
