# Generated by Django 5.2.1 on 2025-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                blank=True,
                default="New",
                help_text="you can set, Ad Action, Earning, Withdrawal, New or Custom",
                max_length=20,
            ),
        ),
    ]
