# Generated by Django 5.2.1 on 2025-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="headline",
            field=models.CharField(max_length=25),
        ),
    ]
