# Generated by Django 5.2.1 on 2025-10-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_ad_headline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ("-updated_at",),
                "permissions": [
                    ("pause_campaign", "Can pause campaigns"),
                    ("start_campaign", "Can start campaigns"),
                    ("activate_campaign", "Can activate reviewed campaigns"),
                    ("decline_campaign", "Can decline reviewed campaigns"),
                    ("resubmit_campaign", "Can resubmit declined campaigns"),
                    (
                        "remoderate_campaign",
                        "Can initiat remoderation active campaign campaigns",
                    ),
                    ("restart_campaign", "Can restart stopped campaigns"),
                ],
            },
        ),
    ]
