# Generated by Django 5.2.1 on 2025-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementmatchlog",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Estimated cost at the time of match",
                max_digits=10,
            ),
        ),
    ]
