# Generated by Django 5.2.1 on 2025-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_placementmatchlog_estimated_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="headline",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ad",
            name="text_content",
            field=models.TextField(),
        ),
    ]
