# Generated by Django 5.2.1 on 2025-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_ad_headline_alter_ad_text_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="link_url",
        ),
        migrations.AddField(
            model_name="ad",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='A list of up to 3 social media links, e.g.,             [{"platform": "X", "url": "https://x.com/username"},                 {"platform": "Website", "url": "https://example.com"}]',
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
