# Generated by Django 5.2.1 on 2025-10-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_ad_link_url_ad_social_links_alter_ad_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adplacement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("running", "Live"),
                    ("rejected", "Rejected"),
                    ("paused", "Paused"),
                    ("stopped", "Stopped"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
