# Generated by Django 5.2.1 on 2025-08-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramvisitorlog",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
